spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/risk_gis_dev

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    com.riskgis: DEBUG
